CREATE TABLE donars(
    id INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
	first VARCHAR(256) NOT NULL,
	last VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    contact VARCHAR(10) NOT NULL,
    bg VARCHAR(1) NOT NULL,
	rh VARCHAR(1) NOT NULL
);
